#!/usr/bin/env python3
"""Gera app/src/main/assets/catalogo.json a partir das listas abaixo.

Para incluir músicas, acrescente (título, artista) na lista do gênero e rode:
    python3 ferramentas/gerar_catalogo.py

Novas músicas devem ir no FIM da lista, para não mudar o código das existentes.
Os códigos seguem o padrão <prefixo do gênero><índice com 3 dígitos> (ex.: 1001).
"""
import json
from pathlib import Path

# (enum Genero, prefixo) -> músicas. Deve bater com data/Genero.kt.
CATALOGO = {
    ("SERTANEJO", 1): [
        ("Evidências", "Chitãozinho & Xororó"),
        ("Fio de Cabelo", "Chitãozinho & Xororó"),
        ("Página de Amigos", "Chitãozinho & Xororó"),
        ("É o Amor", "Zezé Di Camargo & Luciano"),
        ("No Dia em Que Eu Saí de Casa", "Zezé Di Camargo & Luciano"),
        ("Pense em Mim", "Leandro & Leonardo"),
        ("Entre Tapas e Beijos", "Leandro & Leonardo"),
        ("Telefone Mudo", "Trio Parada Dura"),
        ("Tocando em Frente", "Almir Sater"),
        ("Chalana", "Almir Sater"),
        ("Boate Azul", "Bruno & Marrone"),
        ("Camaro Amarelo", "Munhoz & Mariano"),
        ("Ai Se Eu Te Pego", "Michel Teló"),
        ("Infiel", "Marília Mendonça"),
        ("Supera", "Marília Mendonça"),
        ("Cuida Bem Dela", "Henrique & Juliano"),
        ("Liberdade Provisória", "Henrique & Juliano"),
        ("Tchê Tchê Rere", "Gusttavo Lima"),
        ("Amo Noite e Dia", "Jorge & Mateus"),
        ("Chora, Me Liga", "João Bosco & Vinícius"),
    ],
    ("MPB", 2): [
        ("Aquarela", "Toquinho"),
        ("O Bêbado e a Equilibrista", "Elis Regina"),
        ("Como Nossos Pais", "Elis Regina"),
        ("Sozinho", "Caetano Veloso"),
        ("O Leãozinho", "Caetano Veloso"),
        ("Andar com Fé", "Gilberto Gil"),
        ("Drão", "Gilberto Gil"),
        ("Anunciação", "Alceu Valença"),
        ("Chão de Giz", "Zé Ramalho"),
        ("Admirável Gado Novo", "Zé Ramalho"),
        ("Oceano", "Djavan"),
        ("Flor de Lis", "Djavan"),
        ("Mania de Você", "Rita Lee"),
        ("Velha Infância", "Tribalistas"),
        ("Travessia", "Milton Nascimento"),
        ("Maria, Maria", "Milton Nascimento"),
        ("O Que É, O Que É?", "Gonzaguinha"),
        ("Ainda Bem", "Vanessa da Mata"),
        ("Telegrama", "Zeca Baleiro"),
        ("Palpite", "Vanessa Rangel"),
    ],
    ("SAMBA", 3): [
        ("Trem das Onze", "Adoniran Barbosa"),
        ("Saudosa Maloca", "Adoniran Barbosa"),
        ("Tiro ao Álvaro", "Adoniran Barbosa"),
        ("O Mundo É um Moinho", "Cartola"),
        ("As Rosas Não Falam", "Cartola"),
        ("Alvorada", "Cartola"),
        ("Canta, Canta, Minha Gente", "Martinho da Vila"),
        ("Não Deixe o Samba Morrer", "Alcione"),
        ("Sufoco", "Alcione"),
        ("Coisinha do Pai", "Beth Carvalho"),
        ("Vou Festejar", "Beth Carvalho"),
        ("Deixa a Vida Me Levar", "Zeca Pagodinho"),
        ("Verdade", "Zeca Pagodinho"),
        ("Maneiras", "Zeca Pagodinho"),
        ("O Show Tem Que Continuar", "Fundo de Quintal"),
        ("Pé na Areia", "Diogo Nogueira"),
    ],
    ("PAGODE", 4): [
        ("Deixa Acontecer", "Grupo Revelação"),
        ("Tá Escrito", "Grupo Revelação"),
        ("Cheia de Manias", "Raça Negra"),
        ("É Tarde Demais", "Raça Negra"),
        ("Essa Tal Liberdade", "Só Pra Contrariar"),
        ("Que Se Chama Amor", "Só Pra Contrariar"),
        ("Marrom Bombom", "Os Morenos"),
        ("Me Apaixonei Pela Pessoa Errada", "Exaltasamba"),
        ("Tá Vendo Aquela Lua", "Exaltasamba"),
        ("Cilada", "Molejo"),
        ("Brincadeira de Criança", "Molejo"),
    ],
    ("FORRO", 5): [
        ("Asa Branca", "Luiz Gonzaga"),
        ("Xote das Meninas", "Luiz Gonzaga"),
        ("Olha pro Céu", "Luiz Gonzaga"),
        ("Sala de Reboco", "Luiz Gonzaga"),
        ("Esperando na Janela", "Gilberto Gil"),
        ("Xote da Alegria", "Falamansa"),
        ("Rindo à Toa", "Falamansa"),
        ("Morena Tropicana", "Alceu Valença"),
        ("Eu Só Quero um Xodó", "Dominguinhos"),
        ("De Volta pro Aconchego", "Elba Ramalho"),
        ("Tareco e Mariola", "Flávio José"),
    ],
    ("AXE", 6): [
        ("Festa", "Ivete Sangalo"),
        ("Sorte Grande", "Ivete Sangalo"),
        ("Canibal", "Ivete Sangalo"),
        ("O Canto da Cidade", "Daniela Mercury"),
        ("Swing da Cor", "Daniela Mercury"),
        ("Beija-Flor", "Timbalada"),
        ("Selva Branca", "Chiclete com Banana"),
        ("Milla", "Netinho"),
        ("Baianidade Nagô", "Banda Mel"),
        ("Segura o Tchan", "É o Tchan"),
    ],
    ("ROCK_NACIONAL", 7): [
        ("Pais e Filhos", "Legião Urbana"),
        ("Tempo Perdido", "Legião Urbana"),
        ("Eduardo e Mônica", "Legião Urbana"),
        ("Faroeste Caboclo", "Legião Urbana"),
        ("Exagerado", "Cazuza"),
        ("Ideologia", "Cazuza"),
        ("Pro Dia Nascer Feliz", "Barão Vermelho"),
        ("Lanterna dos Afogados", "Os Paralamas do Sucesso"),
        ("Meu Erro", "Os Paralamas do Sucesso"),
        ("Epitáfio", "Titãs"),
        ("Sonífera Ilha", "Titãs"),
        ("Flores", "Titãs"),
        ("Primeiros Erros", "Capital Inicial"),
        ("Infinita Highway", "Engenheiros do Hawaii"),
        ("Pelados em Santos", "Mamonas Assassinas"),
        ("Mulher de Fases", "Raimundos"),
        ("Anna Júlia", "Los Hermanos"),
        ("Garota Nacional", "Skank"),
        ("Vamos Fugir", "Skank"),
        ("Do Seu Lado", "Jota Quest"),
        ("Fácil", "Jota Quest"),
    ],
    ("BOSSA_NOVA", 8): [
        ("Garota de Ipanema", "Tom Jobim"),
        ("Wave", "Tom Jobim"),
        ("Corcovado", "Tom Jobim"),
        ("Insensatez", "Tom Jobim"),
        ("Samba de Uma Nota Só", "Tom Jobim"),
        ("Águas de Março", "Elis Regina & Tom Jobim"),
        ("Chega de Saudade", "João Gilberto"),
        ("Desafinado", "João Gilberto"),
        ("O Barquinho", "Nara Leão"),
        ("Eu Sei Que Vou Te Amar", "Vinicius de Moraes"),
        ("Tarde em Itapoã", "Vinicius de Moraes & Toquinho"),
        ("Samba de Verão", "Marcos Valle"),
    ],
    ("FUNK", 9): [
        ("Rap da Felicidade", "Cidinho & Doca"),
        ("Glamurosa", "MC Marcinho"),
        ("Show das Poderosas", "Anitta"),
        ("Vai Malandra", "Anitta"),
        ("Envolver", "Anitta"),
        ("Baile de Favela", "MC João"),
        ("Bum Bum Tam Tam", "MC Fioti"),
        ("Olha a Explosão", "MC Kevinho"),
        ("Tá Tranquilo, Tá Favorável", "MC Bin Laden"),
    ],
    ("GOSPEL", 10): [
        ("Raridade", "Anderson Freire"),
        ("Ressuscita-me", "Aline Barros"),
        ("Casa do Pai", "Aline Barros"),
        ("Faz um Milagre em Mim", "Regis Danese"),
        ("Advogado Fiel", "Bruna Karla"),
        ("Galileu", "Fernandinho"),
        ("Deus Me Ama", "Thalles Roberto"),
        ("Aquieta Minh'alma", "Ministério Zoe"),
        ("Todavia Me Alegrarei", "Samuel Messias"),
    ],
    ("BREGA_ROMANTICA", 11): [
        ("Detalhes", "Roberto Carlos"),
        ("Emoções", "Roberto Carlos"),
        ("Como É Grande o Meu Amor por Você", "Roberto Carlos"),
        ("Amada Amante", "Roberto Carlos"),
        ("Cama e Mesa", "Roberto Carlos"),
        ("Sentado à Beira do Caminho", "Erasmo Carlos"),
        ("Ternura", "Wanderléa"),
        ("Garçom", "Reginaldo Rossi"),
        ("Fuscão Preto", "Almir Rogério"),
        ("Eu Não Sou Cachorro, Não", "Waldick Soriano"),
        ("Pare de Tomar a Pílula", "Odair José"),
        ("Eu Vou Tirar Você Desse Lugar", "Odair José"),
        ("Fogo e Paixão", "Wando"),
        ("Sonhos", "Peninha"),
        ("Você Não Vale Nada", "Calcinha Preta"),
    ],
    # Cantigas de domínio público: as 8 primeiras já vêm com letra sincronizada.
    ("FOLCLORE_INFANTIL", 12): [
        ("Ciranda, Cirandinha", "Cantiga popular"),
        ("Peixe Vivo", "Cantiga popular"),
        ("Escravos de Jó", "Cantiga popular"),
        ("O Cravo Brigou com a Rosa", "Cantiga popular"),
        ("Marcha Soldado", "Cantiga popular"),
        ("Atirei o Pau no Gato", "Cantiga popular"),
        ("Se Essa Rua Fosse Minha", "Cantiga popular"),
        ("Alecrim Dourado", "Cantiga popular"),
        ("Borboletinha", "Cantiga popular"),
        ("Pirulito Que Bate Bate", "Cantiga popular"),
        ("Sapo Não Lava o Pé", "Cantiga popular"),
        ("Samba Lelê", "Cantiga popular"),
    ],
}


def main() -> None:
    musicas = []
    for (genero, prefixo), lista in CATALOGO.items():
        for i, (titulo, artista) in enumerate(lista, start=1):
            musicas.append({
                "codigo": prefixo * 1000 + i,
                "titulo": titulo,
                "artista": artista,
                "genero": genero,
            })
    destino = Path(__file__).resolve().parent.parent / "app/src/main/assets/catalogo.json"
    destino.write_text(json.dumps(musicas, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"{len(musicas)} músicas gravadas em {destino}")


if __name__ == "__main__":
    main()
