#!/usr/bin/env python3
"""Gera o catálogo de músicas (gêneros + músicas) do Karaokê Brasil.

Grava em dois lugares:
  servidor/catalogo.json           -> lido pelo app pela internet (não precisa recompilar)
  app/src/main/assets/catalogo.json -> cópia embutida, usada sem internet

Para incluir músicas, acrescente (título, artista) NO FIM da lista do gênero.
Para criar um gênero, acrescente um novo item em GENEROS com um prefixo inédito.
Depois rode:  python3 ferramentas/gerar_catalogo.py   e faça commit/push.

Os números seguem o padrão <prefixo><índice com 3 dígitos> (ex.: 1001). Não reordene
as listas: isso muda os números e desassocia letras/áudios já publicados.
"""
import json
from pathlib import Path

GENEROS = [
    {
        "id": "sertanejo", "nome": "Sertanejo", "cor": "#D4A017", "prefixo": 1,
        "musicas": [
            ("Evidências", "Chitãozinho & Xororó"),
            ("Fio de Cabelo", "Chitãozinho & Xororó"),
            ("Página de Amigos", "Chitãozinho & Xororó"),
            ("É o Amor", "Zezé Di Camargo & Luciano"),
            ("No Dia em Que Eu Saí de Casa", "Zezé Di Camargo & Luciano"),
            ("Pense em Mim", "Leandro & Leonardo"),
            ("Entre Tapas e Beijos", "Leandro & Leonardo"),
            ("Telefone Mudo", "Trio Parada Dura"),
            ("Tocando em Frente", "Almir Sater"),
            ("Chalana", "Almir Sater"),
            ("Boate Azul", "Bruno & Marrone"),
            ("Camaro Amarelo", "Munhoz & Mariano"),
            ("Ai Se Eu Te Pego", "Michel Teló"),
            ("Infiel", "Marília Mendonça"),
            ("Supera", "Marília Mendonça"),
            ("Cuida Bem Dela", "Henrique & Juliano"),
            ("Liberdade Provisória", "Henrique & Juliano"),
            ("Tchê Tchê Rere", "Gusttavo Lima"),
            ("Amo Noite e Dia", "Jorge & Mateus"),
            ("Chora, Me Liga", "João Bosco & Vinícius"),
            ("Nuvem de Lágrimas", "Chitãozinho & Xororó"),
            ("Galopeira", "Chitãozinho & Xororó"),
            ("Estrada da Vida", "Milionário & José Rico"),
            ("Ainda Ontem Chorei de Saudade", "João Mineiro & Marciano"),
            ("Seu Amor Ainda É Tudo", "João Mineiro & Marciano"),
            ("Largado às Traças", "Zé Neto & Cristiano"),
            ("Notificação Preferida", "Zé Neto & Cristiano"),
            ("Ciumeira", "Marília Mendonça"),
            ("Todo Mundo Vai Sofrer", "Marília Mendonça"),
            ("Propaganda", "Jorge & Mateus"),
            ("Vidro Fumê", "Bruno & Marrone"),
            ("Dormi na Praça", "Bruno & Marrone"),
            ("Romaria", "Renato Teixeira"),
            ("O Menino da Porteira", "Sérgio Reis"),
            ("Tristeza do Jeca", "Tonico & Tinoco"),
            ("Chico Mineiro", "Tonico & Tinoco"),
            ("Majestade o Sabiá", "Roberta Miranda"),
            ("Vá Com Deus", "Roberta Miranda"),
        ],
    },
    {
        "id": "pop_nacional", "nome": "POP Nacional", "cor": "#9B5DE5", "prefixo": 2,
        "musicas": [
            ("Pais e Filhos", "Legião Urbana"),
            ("Tempo Perdido", "Legião Urbana"),
            ("Eduardo e Mônica", "Legião Urbana"),
            ("Faroeste Caboclo", "Legião Urbana"),
            ("Exagerado", "Cazuza"),
            ("Ideologia", "Cazuza"),
            ("Pro Dia Nascer Feliz", "Barão Vermelho"),
            ("Lanterna dos Afogados", "Os Paralamas do Sucesso"),
            ("Meu Erro", "Os Paralamas do Sucesso"),
            ("Epitáfio", "Titãs"),
            ("Sonífera Ilha", "Titãs"),
            ("Flores", "Titãs"),
            ("Primeiros Erros", "Capital Inicial"),
            ("Natasha", "Capital Inicial"),
            ("Infinita Highway", "Engenheiros do Hawaii"),
            ("Pelados em Santos", "Mamonas Assassinas"),
            ("Mulher de Fases", "Raimundos"),
            ("Anna Júlia", "Los Hermanos"),
            ("Garota Nacional", "Skank"),
            ("Vamos Fugir", "Skank"),
            ("Resposta", "Skank"),
            ("Do Seu Lado", "Jota Quest"),
            ("Fácil", "Jota Quest"),
            ("Só Hoje", "Jota Quest"),
            ("Como uma Onda", "Lulu Santos"),
            ("Tempos Modernos", "Lulu Santos"),
            ("Toda Forma de Amor", "Lulu Santos"),
            ("Como Eu Quero", "Kid Abelha"),
            ("Fixação", "Kid Abelha"),
            ("Pintura Íntima", "Kid Abelha"),
            ("Lança Perfume", "Rita Lee"),
            ("Ovelha Negra", "Rita Lee"),
            ("Malandragem", "Cássia Eller"),
            ("Por Enquanto", "Cássia Eller"),
            ("Inútil", "Ultraje a Rigor"),
            ("Ciúme", "Ultraje a Rigor"),
            ("Você Não Soube Me Amar", "Blitz"),
            ("Olhar 43", "RPM"),
            ("Rádio Pirata", "RPM"),
            ("Fullgás", "Marina Lima"),
            ("Só os Loucos Sabem", "Charlie Brown Jr."),
            ("Proibida pra Mim", "Charlie Brown Jr."),
            ("Admirável Chip Novo", "Pitty"),
            ("Me Adora", "Pitty"),
            ("Festa", "Ivete Sangalo"),
            ("Sorte Grande", "Ivete Sangalo"),
            ("O Canto da Cidade", "Daniela Mercury"),
            ("Show das Poderosas", "Anitta"),
            ("Envolver", "Anitta"),
        ],
    },
    {
        "id": "bregas", "nome": "Bregas", "cor": "#D63384", "prefixo": 3,
        "musicas": [
            ("Garçom", "Reginaldo Rossi"),
            ("A Raposa e as Uvas", "Reginaldo Rossi"),
            ("Leviana", "Reginaldo Rossi"),
            ("Princesa", "Amado Batista"),
            ("Secretária", "Amado Batista"),
            ("O Fruto do Nosso Amor", "Amado Batista"),
            ("Pare de Tomar a Pílula", "Odair José"),
            ("Eu Vou Tirar Você Desse Lugar", "Odair José"),
            ("Eu Não Sou Cachorro, Não", "Waldick Soriano"),
            ("Você Não Me Ensinou a Te Esquecer", "Fernando Mendes"),
            ("A Desconhecida", "Fernando Mendes"),
            ("Fogo e Paixão", "Wando"),
            ("Moça", "Wando"),
            ("Sorria, Sorria", "Evaldo Braga"),
            ("A Cruz Que Carrego", "Evaldo Braga"),
            ("Os Brutos Também Amam", "Agnaldo Timóteo"),
            ("Aguenta Coração", "José Augusto"),
            ("Fuscão Preto", "Almir Rogério"),
            ("Você Não Vale Nada", "Calcinha Preta"),
            ("Sonhos", "Peninha"),
            ("Não Está Sendo Fácil", "Kátia"),
        ],
    },
    {
        "id": "sambas", "nome": "Sambas", "cor": "#2A9D8F", "prefixo": 4,
        "musicas": [
            ("Trem das Onze", "Adoniran Barbosa"),
            ("Saudosa Maloca", "Adoniran Barbosa"),
            ("Tiro ao Álvaro", "Adoniran Barbosa"),
            ("O Mundo É um Moinho", "Cartola"),
            ("As Rosas Não Falam", "Cartola"),
            ("Alvorada", "Cartola"),
            ("Canta, Canta, Minha Gente", "Martinho da Vila"),
            ("Mulheres", "Martinho da Vila"),
            ("Não Deixe o Samba Morrer", "Alcione"),
            ("Sufoco", "Alcione"),
            ("Coisinha do Pai", "Beth Carvalho"),
            ("Vou Festejar", "Beth Carvalho"),
            ("Deixa a Vida Me Levar", "Zeca Pagodinho"),
            ("Verdade", "Zeca Pagodinho"),
            ("Maneiras", "Zeca Pagodinho"),
            ("O Show Tem Que Continuar", "Fundo de Quintal"),
            ("Conselho", "Almir Guineto"),
            ("Foi um Rio Que Passou em Minha Vida", "Paulinho da Viola"),
            ("Retalhos de Cetim", "Benito di Paula"),
            ("Charlie Brown", "Benito di Paula"),
            ("Sonho Meu", "Maria Bethânia"),
            ("Pé na Areia", "Diogo Nogueira"),
            ("Deixa Acontecer", "Grupo Revelação"),
            ("Tá Escrito", "Grupo Revelação"),
            ("Cheia de Manias", "Raça Negra"),
            ("É Tarde Demais", "Raça Negra"),
            ("Essa Tal Liberdade", "Só Pra Contrariar"),
            ("Que Se Chama Amor", "Só Pra Contrariar"),
            ("Marrom Bombom", "Os Morenos"),
            ("Me Apaixonei Pela Pessoa Errada", "Exaltasamba"),
            ("Tá Vendo Aquela Lua", "Exaltasamba"),
            ("Cilada", "Molejo"),
        ],
    },
    {
        "id": "forro", "nome": "Forró", "cor": "#F4A261", "prefixo": 5,
        "musicas": [
            ("Asa Branca", "Luiz Gonzaga"),
            ("Xote das Meninas", "Luiz Gonzaga"),
            ("Olha pro Céu", "Luiz Gonzaga"),
            ("Sala de Reboco", "Luiz Gonzaga"),
            ("Qui Nem Jiló", "Luiz Gonzaga"),
            ("Assum Preto", "Luiz Gonzaga"),
            ("Vida de Viajante", "Luiz Gonzaga"),
            ("Pagode Russo", "Luiz Gonzaga"),
            ("Forró no Escuro", "Luiz Gonzaga"),
            ("Esperando na Janela", "Gilberto Gil"),
            ("Xote da Alegria", "Falamansa"),
            ("Rindo à Toa", "Falamansa"),
            ("Xote dos Milagres", "Falamansa"),
            ("Oh! Chuva", "Falamansa"),
            ("Morena Tropicana", "Alceu Valença"),
            ("Eu Só Quero um Xodó", "Dominguinhos"),
            ("Isso Aqui Tá Bom Demais", "Dominguinhos"),
            ("De Volta pro Aconchego", "Elba Ramalho"),
            ("Tareco e Mariola", "Flávio José"),
            ("Chiclete com Banana", "Jackson do Pandeiro"),
            ("O Canto da Ema", "Jackson do Pandeiro"),
            ("Sebastiana", "Jackson do Pandeiro"),
        ],
    },
    {
        "id": "boleros", "nome": "Boleros", "cor": "#B5179E", "prefixo": 6,
        "musicas": [
            ("A Volta do Boêmio", "Nelson Gonçalves"),
            ("Negue", "Nelson Gonçalves"),
            ("Fica Comigo Esta Noite", "Nelson Gonçalves"),
            ("Deusa do Asfalto", "Nelson Gonçalves"),
            ("Meu Vício É Você", "Nelson Gonçalves"),
            ("Nada Além", "Orlando Silva"),
            ("Ninguém Me Ama", "Nora Ney"),
            ("Vingança", "Linda Batista"),
            ("Nervos de Aço", "Lupicínio Rodrigues"),
            ("Dois pra Lá, Dois pra Cá", "Elis Regina"),
            ("Tortura de Amor", "Waldick Soriano"),
            ("A Noite do Meu Bem", "Dolores Duran"),
            ("Castigo", "Dolores Duran"),
            ("Chuvas de Verão", "Caetano Veloso"),
        ],
    },
    {
        "id": "mpb", "nome": "MPB", "cor": "#2E86AB", "prefixo": 7,
        "musicas": [
            ("Aquarela", "Toquinho"),
            ("O Bêbado e a Equilibrista", "Elis Regina"),
            ("Como Nossos Pais", "Elis Regina"),
            ("Sozinho", "Caetano Veloso"),
            ("O Leãozinho", "Caetano Veloso"),
            ("Sampa", "Caetano Veloso"),
            ("Andar com Fé", "Gilberto Gil"),
            ("Drão", "Gilberto Gil"),
            ("Anunciação", "Alceu Valença"),
            ("Chão de Giz", "Zé Ramalho"),
            ("Admirável Gado Novo", "Zé Ramalho"),
            ("Oceano", "Djavan"),
            ("Flor de Lis", "Djavan"),
            ("Meu Bem Querer", "Djavan"),
            ("Mania de Você", "Rita Lee"),
            ("Velha Infância", "Tribalistas"),
            ("Travessia", "Milton Nascimento"),
            ("Maria, Maria", "Milton Nascimento"),
            ("O Que É, O Que É?", "Gonzaguinha"),
            ("Ainda Bem", "Vanessa da Mata"),
            ("Telegrama", "Zeca Baleiro"),
            ("Palpite", "Vanessa Rangel"),
            ("Amor I Love You", "Marisa Monte"),
            ("Fico Assim Sem Você", "Adriana Calcanhotto"),
            ("Canteiros", "Fagner"),
            ("Espumas ao Vento", "Fagner"),
            ("País Tropical", "Jorge Ben Jor"),
            ("Taj Mahal", "Jorge Ben Jor"),
            ("A Banda", "Chico Buarque"),
            ("Construção", "Chico Buarque"),
            ("Cálice", "Chico Buarque"),
            ("Pra Não Dizer Que Não Falei das Flores", "Geraldo Vandré"),
            ("Carinhoso", "Pixinguinha"),
            ("Detalhes", "Roberto Carlos"),
            ("Emoções", "Roberto Carlos"),
            ("Como É Grande o Meu Amor por Você", "Roberto Carlos"),
            ("Amada Amante", "Roberto Carlos"),
            ("Cama e Mesa", "Roberto Carlos"),
            ("Sentado à Beira do Caminho", "Erasmo Carlos"),
            ("Ternura", "Wanderléa"),
            ("Garota de Ipanema", "Tom Jobim"),
            ("Wave", "Tom Jobim"),
            ("Corcovado", "Tom Jobim"),
            ("Águas de Março", "Elis Regina & Tom Jobim"),
            ("Chega de Saudade", "João Gilberto"),
            ("Desafinado", "João Gilberto"),
            ("O Barquinho", "Nara Leão"),
            ("Eu Sei Que Vou Te Amar", "Vinicius de Moraes"),
            ("Tarde em Itapoã", "Vinicius de Moraes & Toquinho"),
            ("Samba de Verão", "Marcos Valle"),
        ],
    },
    # Cantigas de domínio público: as 8 primeiras já vêm com letra sincronizada.
    {
        "id": "folclore_infantil", "nome": "Folclore & Infantil", "cor": "#00B4D8", "prefixo": 12,
        "musicas": [
            ("Ciranda, Cirandinha", "Cantiga popular"),
            ("Peixe Vivo", "Cantiga popular"),
            ("Escravos de Jó", "Cantiga popular"),
            ("O Cravo Brigou com a Rosa", "Cantiga popular"),
            ("Marcha Soldado", "Cantiga popular"),
            ("Atirei o Pau no Gato", "Cantiga popular"),
            ("Se Essa Rua Fosse Minha", "Cantiga popular"),
            ("Alecrim Dourado", "Cantiga popular"),
            ("Borboletinha", "Cantiga popular"),
            ("Pirulito Que Bate Bate", "Cantiga popular"),
            ("Sapo Não Lava o Pé", "Cantiga popular"),
            ("Samba Lelê", "Cantiga popular"),
        ],
    },
]


def main() -> None:
    prefixos = [g["prefixo"] for g in GENEROS]
    ids = [g["id"] for g in GENEROS]
    assert len(set(prefixos)) == len(prefixos), "prefixos de gênero repetidos"
    assert len(set(ids)) == len(ids), "ids de gênero repetidos"

    generos, musicas = [], []
    for g in GENEROS:
        assert len(g["musicas"]) < 1000, f"{g['id']}: máximo de 999 músicas por gênero"
        generos.append({"id": g["id"], "nome": g["nome"], "cor": g["cor"]})
        for i, (titulo, artista) in enumerate(g["musicas"], start=1):
            musicas.append({
                "codigo": g["prefixo"] * 1000 + i,
                "titulo": titulo,
                "artista": artista,
                "genero": g["id"],
            })

    conteudo = json.dumps({"generos": generos, "musicas": musicas}, ensure_ascii=False, indent=1) + "\n"
    raiz = Path(__file__).resolve().parent.parent
    for destino in (raiz / "servidor/catalogo.json", raiz / "app/src/main/assets/catalogo.json"):
        destino.write_text(conteudo, encoding="utf-8")
        print(f"{len(musicas)} músicas em {len(generos)} gêneros -> {destino.relative_to(raiz)}")


if __name__ == "__main__":
    main()
